version: "0.1"

services:
    dev:
        container_name: wheat-dev
        image: wheat:0.1
        volumes:
            - ./:/workspace
            #- /data_rw/competitions/open_cities/:/workspace/old-data/
            #- /data_rw/competitions/open_cities_refactor/:/workspace/data/
        working_dir: /workspace
        ipc: host
        runtime: nvidia
        command: sleep infinity
