---
seed: 1234

experiment_name: "effdet4"
fold: 2
image_size: 512
experiment_run: "run1"

optimizer:
    type: AdamW
    start_lr: 1e-3
    min_lr: 1e-6 
    
scheduler:
  type: ReduceOnPlateu
  factor: 0.2
  loss_delta: 1e-4
  min_lr: 1e-6 

model:
  type: EfficientDet4
  pretrained: True
  encoder: effnet
  classes: 1
  encoder_weights: imagenet

training:  
  n_epochs: 60 
  early_stop: True
  overall_patience: 10
  num_workers: 2
  batch_size: 4
  save_path: 
  gpu_number: 1  

train_augs:  
    transforms:
    __class_fullname__: albumentations.core.composition.Compose
    bbox_params: 
        'format': 'pascal_voc'    
        'label_fields': ['labels']
    p: 1
    transforms:
      - __class_fullname__: albumentations.augmentations.transforms.RandomSizedCrop
        min_max_height: (800, 800)
        height: 1024 
        width: 1024 
        p: 0.5    
      - __class_fullname__: albumentations.augmentations.transforms.OneOf
        p: 0.9      
      - __class_fullname__: albumentations.augmentations.transforms.HueSaturationValue
        hue_shift_limit: 0.2 
        sat_shift_limit: 0.2
        val_shift_limit: 0.2 
        p: 0.9
      - __class_fullname__: albumentations.augmentations.transforms.RandomBrightnessContrast
        brightness_limit: 0.2
        contrast_limit: 0.2 
        p: 0.9
      - __class_fullname__: albumentations.augmentations.transforms.ToGray
        p: 0.01        
      - __class_fullname__: albumentations.augmentations.transforms.HorizontalFlip        
        p: 0.5     
      - __class_fullname__: albumentations.augmentations.transforms.VerticalFlip   
        p: 0.5  
      - __class_fullname__: albumentations.augmentations.transforms.Resize
        height: image_size 
        width: image_size
        p: 1
      - __class_fullname__: albumentations.augmentations.transforms.Cutout 
        num_holes: 8 
        max_h_size: image_size // 8 
        max_w_size: image_size // 8 
        fill_value=0: 
        p: 0.5
      - __class_fullname__: normalize        
        max_pixel_value: 255.0
        mean:
          - 0.485
          - 0.456
          - 0.406        
        std:
          - 0.229
          - 0.224
          - 0.225

val_aug:
  transform:
    __class_fullname__: albumentations.core.composition.Compose
    bbox_params: 
        'format': 'pascal_voc'    
        'label_fields': ['labels']
    p: 1
    transforms:
        - __class_fullname__: albumentations.augmentations.transforms.Resize
        height: image_size 
        width: image_size
        p: 1
      - __class_fullname__: normalize        
        max_pixel_value: 255.0
        mean:
          - 0.485
          - 0.456
          - 0.406        
        std:
          - 0.229
          - 0.224
          - 0.225