---
seed: 1234

experiment_name: "2020-05-19"

optimizer:
    type: RAdam
    lr: 0.0001

scheduler:
  type: midv500models.schedulers.PolyLR
  max_iter: 40

model:
  type: EfficientNet
  pretrained: True
  encoder: resnet34
  classes: 1
  encoder_weights: imagenet

training:  
  early_stop: False
  save_path: ./
  gpus: 2
  num_workers: 4

  amp_level: O1
  max_epochs: 40
  gradient_clip_val: 3
  benchmark: True



train_parameters:
  batch_size: 32

  precision: 16

test_parameters:
  batch_size: 2

checkpoint_callback:
  type: pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint
  filepath: "2020-05-19"
  monitor: val_iou
  verbose: True
  mode: max
  save_top_k: -1

val_parameters:
  batch_size: 32

train_aug:
  transform:
    __class_fullname__: albumentations.core.composition.Compose
    bbox_params: null
    keypoint_params: null
    p: 1
    transforms:
      - __class_fullname__: albumentations.augmentations.transforms.LongestMaxSize
        always_apply: False
        max_size: 768
        p: 1
      - __class_fullname__: albumentations.augmentations.transforms.PadIfNeeded
        min_height: 768
        min_width: 768
        always_apply: False
        border_mode: 0
        p: 1
      - __class_fullname__: albumentations.augmentations.transforms.RandomCrop
        always_apply: false
        p: 1
        height: 512
        width: 512
      - __class_fullname__: albumentations.augmentations.transforms.ShiftScaleRotate
        always_apply: false
        p: 1
        scale_limit: 0.2
        rotate_limit: 5
        border_mode: 0
        value: 0
        mask_value: 0
      - __class_fullname__: albumentations.augmentations.transforms.HorizontalFlip
        always_apply: false
        p: 0.5
      - __class_fullname__: albumentations.augmentations.transforms.RandomRotate90
        always_apply: false
        p: 1
      - __class_fullname__: albumentations.augmentations.transforms.RandomBrightnessContrast
        always_apply: false
        p: 0.5
      - __class_fullname__: albumentations.augmentations.transforms.RandomGamma
        always_apply: false
        p: 0.5
      - __class_fullname__: albumentations.augmentations.transforms.HueSaturationValue
        always_apply: false
        p: 0.5
      - __class_fullname__: albumentations.augmentations.transforms.Blur
        always_apply: false
        p: 0.5
      - __class_fullname__: albumentations.augmentations.transforms.JpegCompression
        always_apply: false
        p: 0.5
        quality_lower: 20
        quality_upper: 95
      - __class_fullname__: albumentations.augmentations.transforms.Normalize
        always_apply: false
        max_pixel_value: 255.0
        mean:
          - 0.485
          - 0.456
          - 0.406
        p: 1
        std:
          - 0.229
          - 0.224
          - 0.225

val_aug:
  transform:
    __class_fullname__: albumentations.core.composition.Compose
    bbox_params: null
    keypoint_params: null
    p: 1
    transforms:
      - __class_fullname__: albumentations.augmentations.transforms.LongestMaxSize
        always_apply: False
        max_size: 768
        p: 1
      - __class_fullname__: albumentations.augmentations.transforms.PadIfNeeded
        min_height: 768
        min_width: 768
        always_apply: False
        border_mode: 0
        p: 1
      - __class_fullname__: albumentations.augmentations.transforms.Normalize
        always_apply: false
        max_pixel_value: 255.0
        mean:
          - 0.485
          - 0.456
          - 0.406
        p: 1
        std:
          - 0.229
          - 0.224
          - 0.225

test_aug:
  transform:
    __class_fullname__: albumentations.core.composition.Compose
    bbox_params: null
    keypoint_params: null
    p: 1
    transforms:
      - __class_fullname__: albumentations.augmentations.transforms.Normalize
        always_apply: false
        max_pixel_value: 255.0
        mean:
          - 0.485
          - 0.456
          - 0.406
        p: 1
        std:
          - 0.229
          - 0.224
          - 0.225